export default {
  locale: 'en',
  messages: {
    siteTitle: 'MERN Starter Blog',
    addPost: 'Add Post',
    switchLanguage: 'Switch Language',
    twitterMessage: 'We are on Twitter',
    by: 'By',
    deletePost: 'Delete Post',
    createNewPost: 'Create new post',
    authorName: 'Author\'s Name',
    postTitle: 'Post Title',
    postContent: 'Post Content',
    submit: 'Submit',
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	}`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	}`,
    nestedDateComment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	} as of {date}`,
    authForm: 'Sign up/Sign in',
    about: 'About',
    jobHistory: 'Job History',
    email: 'Email',
    password: 'Password',
    passwordConfirmation: 'Password Confirmation',
    signUp: 'Sign up',
    signIn: 'Sign in',
    or: 'Or',
    facebook: 'Facebook',
    profile: 'Profile',
    signOut: 'Sign Out',
    unknown: 'unknown',
    save: 'Save',
    cancel: 'Cancel',
    nameDialog: 'Name',
    yourName: 'Your Name',
    nationalityDialog: 'Nationality',
    addressDialog: 'Address',
    feeDialog: 'Fee',
    yourNationality: 'Your nationality',
    yourAddress: 'Your address',
    yourFee: 'Your stated Fee',
    feeCheckBox: 'Will you charge for a meet up',
    genderDialog: 'Gender',
    male: 'Male',
    female: 'Female',
    yearOfBirthDialog: 'Year of Birth',
    teachingAbility: 'Can you teach English?',
    name: `Name: {name}`,
    nationality: `Nationality: {nationality}`,
    gender: `Gender: {gender}`,
    yearOfBirth: `Year of Birth: {yearOfBirth}`,
    address: `Address: `,
    fee: `Fee: {fee}`,
    job: `Job: {job}`,
    workplace: `Workplace: {workplace}`,
    workTime: `For {workTime}`,
    likes: `{likes} likes`,
    follows: `{follows} follows`,
    editAbout: `Edit About`,
    certificate: `Have you achieve the certificate?`,
    marks: `Score Bands`,
    jobHis: 'Job',
    workplaceHis: 'Work place',
    fromHis: 'From',
    toHis: 'To',
    upload: 'Upload',
    designed: 'Designed by',
    power: 'Power by',

    search: 'Search',
    typeaheadPH: 'Search by name, city, district and fee',
    nomatch: 'No match found',
    City: 'City',
    District: 'District',
    Fee: 'Fee',

    none: 'None',
    500: 'above 500 thounsand',
    1000: 'above 1 million',

    // city name
    hcm: 'Ho Chi Minh',
    // district name
    quan1: 'District 1',
    quan2: 'District 2',

    chatWith: 'Chat with',
    group: 'Group ',

    like: 'Like',
    liked: 'Liked',
    follow: 'Follow',
    followed: 'Followed',
    chat: 'Chat',

    speaking: 'Speaking: {speaking}',
    listening: 'Listening: {listening}',
    writing: 'Writing: {writing}',
    reading: 'Reading: {reading}',
  },
};
