export default {
  locale: 'vn',
  messages: {
    siteTitle: 'MERN blog mẫu',
    addPost: 'Thêm bài',
    switchLanguage: 'Đổi ngôn ngữ',
    twitterMessage: 'Chúng tôi có mặt trên Twitter',
    by: 'bởi',
    deletePost: 'Xóa bài',
    createNewPost: 'Tạo bài mới',
    authorName: 'Tên tác giả',
    postTitle: 'Tiêu đề',
    postContent: 'Nội dung',
    submit: 'Gửi',
    comment: `người dùng {name} {value, plural,
    	  =0 {Không có bình luận}
    	  =1 {có # bình luận}
    	  other {có # bình luận}
    	}`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	}`,
    nestedDateComment: `Người dùng {name} {value, plural,
    	  =0 {Không có bình luận}
    	  =1 {có # bình luận}
    	  other {có # bình luận}
    	} as of {date}`,
    authForm: 'Đăng ký/đăng nhập',
    about: 'Giới thiệu',
    email: 'Địa chỉ email',
    password: 'Mật khẩu',
    passwordConfirmation: 'Xác nhận mật khẩu',
    signUp: 'Đăng ký',
    signIn: 'Đăng nhập',
    or: 'hoặc',
    facebook: 'Facebook',
    profile: 'Trang cá nhân',
    signOut: 'Đăng xuất',
    unknown: 'Vô danh',
    save: 'Lưu',
    cancel: 'Hủy bỏ',
    nameDialog: 'Tên',
    yourName: 'Tên của bạn',
    nationalityDialog: 'Quốc tịch',
    addressDialog: 'Địa chỉ',
    feeDialog: 'Phí',
    yourNationality: 'Quốc tịch của bạn',
    yourAddress: 'Địa chỉ của bạn',
    feeCheckBox: 'Có thu phí không?',
    yourFee: 'Mức phí đưa ra',
    genderDialog: 'Giới tính',
    male: 'Nam',
    female: 'Nữ',
    yearOfBirthDialog: 'Năm sinh',
    teachingAbility: 'Bạn có thể giảng dạy tiếng anh không?',
    name: `Tên: {name}`,
    nationality: `Quốc tịch: {nationality}`,
    gender: `Giới tính: {gender}`,
    yearOfBirth: `Năm sinh: {yearOfBirth}`,
    address: `Địa chỉ: `,
    fee: `Phí: {fee}`,
    job: `Nghề nghiệp: {job}`,
    workplace: `Nơi công tác: {workplace}`,
    workTime: `Được {workTime}`,
    likes: `{likes} lượt thích`,
    follows: `{follows} lượt theo dõi`,
    editAbout: `Chỉnh sửa`,
    certificate: `Bạn đã thi chứng chỉ chưa?`,
    jobHistory: 'Tiểu sử nghề nghiệp',
    marks: `Điểm đạt được`,
    jobHis: 'Nghề nghiệp',
    workplaceHis: 'Nơi làm việc',
    fromHis: 'Từ',
    toHis: 'Đến',
    upload: 'Tải hình',
    designed: 'Thực hiện bởi',
    power: 'Trên nền tảng',

    search: 'Tìm',
    typeaheadPH: 'Tìm theo tên, thành phố, quận và chi phí',
    nomatch: 'Không tìm thấy kết quả',
    City: 'Thành phố',
    District: 'Quận',
    Fee: 'Chi phí',

    none: 'Không tính phí',
    500: 'trên 500 ngàn',
    1000: 'trên 1 triệu',

    // city name
    hcm: 'Hồ Chí Minh',
    // district name
    quan1: 'Quận 1',
    quan2: 'Quận 2',

    chatWith: 'Trò chuyện cùng',
    group: 'Nhóm ',

    like: 'Thích',
    liked: 'Đã thích',
    follow: 'Theo dõi',
    followed: 'Đã theo dõi',
    chat: 'Trò chuyện',

    speaking: 'Nói: {speaking}',
    listening: 'Nghe: {listening}',
    writing: 'Viết: {writing}',
    reading: 'Đọc: {reading}',
  },
};
